version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: docker-dummy-b_php
    volumes:
      - ./src:/var/www/
      - ~/.ssh:/root/.ssh
    env_file:
      - ./.env
